image: way2web/pipeline-apps:latest

pipelines:
    default:
        - step:
            caches:
                - node
            script:
                - ./bitbucket-pipelines/assets.sh
    branches:
        default:
            - step:
                caches:
                    - node
                script:
                    - ./bitbucket-pipelines/assets.sh
        release:
            - step:
                caches:
                    - node
                script:
                    - ./bitbucket-pipelines/assets.sh
                    - ./bitbucket-pipelines/npm.sh
